HW 01
bansheewaltz/2024-2-VK-EDU-Frontend-A-Grevtsov pull request #1
Opened 2024-09-30 17:00 UTC by bansheewaltz

# Домашнее задание № 1

Прошу @martinkomitsky, @haseprogram, @kgrechin или @1marbur1 проверить его.

Что было сделано:
* Написаны реализации заданных функций
* Написаны тесты к `convertBytesToHuman()`

2024-10-01 17:12 UTC, 1MarBur1 requested changes

2024-10-01 17:12 UTC, 1MarBur1 commented on convertBytesToHuman.js
> +  }
Что если передать Infinity?

2024-10-01 17:12 UTC, 1MarBur1 commented on convertBytesToHuman.js
> +  value = parseFloat(value.toFixed(2)); // remove insignificant zeroes
гуд, если что можно использовать просто Number() или +

2024-10-27 18:05 UTC, martinkomitsky commented
@bansheewaltz будут ли исправления?

2024-11-09 15:54 UTC, martinkomitsky approved these changes
7

2024-11-09 15:54 UTC, merged